//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace application_adoption.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("application_adoption.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _D9D9D9 {
            get {
                object obj = ResourceManager.GetObject("#D9D9D9", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap abstractform {
            get {
                object obj = ResourceManager.GetObject("abstractform", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap add_photo_plus_upload_icon_1320184041118793911_48 {
            get {
                object obj = ResourceManager.GetObject("add+photo+plus+upload+icon-1320184041118793911_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ANICARE {
            get {
                object obj = ResourceManager.GetObject("ANICARE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ANICARE__1_ {
            get {
                object obj = ResourceManager.GetObject("ANICARE (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap animal_wildlife_feline_1320568503309200273_48 {
            get {
                object obj = ResourceManager.GetObject("animal+wildlife+feline-1320568503309200273_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ant_design___outlined_icons_stock_1324441629900553096_32 {
            get {
                object obj = ResourceManager.GetObject("ant+design+++outlined+icons+stock-1324441629900553096_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap avatar_circle_male_profile_user_icon_1320196710301016992_48 {
            get {
                object obj = ResourceManager.GetObject("avatar+circle+male+profile+user+icon-1320196710301016992_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap avatar_circle_male_profile_user_icon_1320196710301016992_481 {
            get {
                object obj = ResourceManager.GetObject("avatar+circle+male+profile+user+icon-1320196710301016992_481", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap avatar_human_male_man_people_person_profile_user_users_icon_1320190727966457290_64 {
            get {
                object obj = ResourceManager.GetObject("avatar+human+male+man+people+person+profile+user+users+icon-1320190727966457290_6" +
                        "4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BIENVENUE_CHEZ_ANICARE {
            get {
                object obj = ResourceManager.GetObject("BIENVENUE CHEZ ANICARE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BIENVENUE_CHEZ_ANICARE__1_ {
            get {
                object obj = ResourceManager.GetObject("BIENVENUE CHEZ ANICARE (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BIENVENUE_CHEZ_ANICARE__2_ {
            get {
                object obj = ResourceManager.GetObject("BIENVENUE CHEZ ANICARE (2)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BIENVENUE_CHEZ_ANICARE1 {
            get {
                object obj = ResourceManager.GetObject("BIENVENUE CHEZ ANICARE1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bigfoot {
            get {
                object obj = ResourceManager.GetObject("bigfoot", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bx_category_alt_1325051853283468208_32 {
            get {
                object obj = ResourceManager.GetObject("bx+category+alt-1325051853283468208_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cancel_delete_garbage_recycle_remove_icon_1320085878741725875_48 {
            get {
                object obj = ResourceManager.GetObject("cancel+delete+garbage+recycle+remove+icon-1320085878741725875_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Connected_16 {
            get {
                object obj = ResourceManager.GetObject("Connected_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap costume_avatar_character_halloween_25_512 {
            get {
                object obj = ResourceManager.GetObject("costume_avatar_character_halloween-25-512", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Deconnecte {
            get {
                object obj = ResourceManager.GetObject("Deconnecte", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap delete_exit_x_icon_1320166084090816488_48 {
            get {
                object obj = ResourceManager.GetObject("delete+exit+x+icon-1320166084090816488_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap delete_remove_trash_trash_bin_trash_can_icon_1320073117929397588_48 {
            get {
                object obj = ResourceManager.GetObject("delete+remove+trash+trash+bin+trash+can+icon-1320073117929397588_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap directions_24px_131987942689909534_32 {
            get {
                object obj = ResourceManager.GetObject("directions+24px-131987942689909534_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap email_letter_mail_icon_1320165660069903496_32 {
            get {
                object obj = ResourceManager.GetObject("email+letter+mail+icon-1320165660069903496_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap equality_gender_male_relationship_sexual_orientation_transgender_icon_1320183803797541484_32 {
            get {
                object obj = ResourceManager.GetObject("equality+gender+male+relationship+sexual+orientation+transgender+icon-13201838037" +
                        "97541484_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap form {
            get {
                object obj = ResourceManager.GetObject("form", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap form1 {
            get {
                object obj = ResourceManager.GetObject("form1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Gérer_les_catégories {
            get {
                object obj = ResourceManager.GetObject("Gérer les catégories", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap help_inkcontober_united_icon_1320183881540886372_48 {
            get {
                object obj = ResourceManager.GetObject("help+inkcontober+united+icon-1320183881540886372_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_disk_disk_icon_disk_line_icon_dvd_icon_icon_1320073118181264386_48 {
            get {
                object obj = ResourceManager.GetObject("icon+disk+disk+icon+disk+line+icon+dvd+icon+icon-1320073118181264386_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap map_point_icon_1320073183505881976_32 {
            get {
                object obj = ResourceManager.GetObject("map+point+icon-1320073183505881976_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Menu_32 {
            get {
                object obj = ResourceManager.GetObject("Menu_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap merge_type_48px_131985219209907007_32 {
            get {
                object obj = ResourceManager.GetObject("merge+type+48px-131985219209907007_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap of_thrones_game_thrones_series_character_avatar_jon_snow_1320568555745862611_64 {
            get {
                object obj = ResourceManager.GetObject("of+thrones+game+thrones+series+character+avatar+jon+snow-1320568555745862611_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap os_x_icon_1320167913307692405_32 {
            get {
                object obj = ResourceManager.GetObject("os+x+icon-1320167913307692405_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap person_security_spy_icon_1320190983084466622_32 {
            get {
                object obj = ResourceManager.GetObject("person+security+spy+icon-1320190983084466622_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap phone_outline_2_131964735288098578_32 {
            get {
                object obj = ResourceManager.GetObject("phone+outline+2-131964735288098578_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap post_share_update_icon_1320184669913435325_48 {
            get {
                object obj = ResourceManager.GetObject("post+share+update+icon-1320184669913435325_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rating_131964753173121821_48 {
            get {
                object obj = ResourceManager.GetObject("rating-131964753173121821_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Sans_titre {
            get {
                object obj = ResourceManager.GetObject("Sans titre", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Sans_titre__1_ {
            get {
                object obj = ResourceManager.GetObject("Sans titre (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Sans_titre__1_1 {
            get {
                object obj = ResourceManager.GetObject("Sans titre (1)1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Sans_titre__1_2 {
            get {
                object obj = ResourceManager.GetObject("Sans titre (1)2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Sans_titre__2_ {
            get {
                object obj = ResourceManager.GetObject("Sans titre (2)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Sans_titre__3_ {
            get {
                object obj = ResourceManager.GetObject("Sans titre (3)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Sans_titre__4_ {
            get {
                object obj = ResourceManager.GetObject("Sans titre (4)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap settings_131964743801424017_32 {
            get {
                object obj = ResourceManager.GetObject("settings-131964743801424017_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Shutdown_32 {
            get {
                object obj = ResourceManager.GetObject("Shutdown_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Subtract_32 {
            get {
                object obj = ResourceManager.GetObject("Subtract_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap upload_icon_upload_line_icon_icon_1320073121636456908_48 {
            get {
                object obj = ResourceManager.GetObject("upload+icon+upload+line+icon+icon-1320073121636456908_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap user_business_man_employee_general_human_member_office_icon_1320183160496301770_48 {
            get {
                object obj = ResourceManager.GetObject("user+business+man+employee+general+human+member+office+icon-1320183160496301770_4" +
                        "8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
